vich_uploader:
    db_driver: orm

    mappings:
     dresseur:
           uri_prefix: /img/dresseur
           upload_destination: '%kernel.project_dir%/public/img/dresseur'

           inject_on_load:  false
           delete_on_update:  true
           delete_on_remove:  true